sil-ai/aqua-api

- bible_routes/v2/verse_routes.py
- queries.py
This presumably wasn't working before, but I guess no one uses it. I need it now, so here's the fix!
> Fix non-working /book route

- queries.py
- review_routes/v2/results_routes.py
This normally orders by more or less ID, but not always! So we need to specify it.
> Order by id for book and text

- models.py
- queries.py
- review_routes/v2/results_routes.py
Sorry - another route for you to convert, Alejandro...! This is to provide the word search feature we are currently implementing in the UI.
> AQUA-182 Add alignmentmatches route

- security_routes/admin_routes.py
- test/test_security_routes/test_admin_routes.py
I haven't been able to build the API locally to run the new test. So we need to check that. But I think the route does what we want it to.
> Unlink user from group

- assessment_routes/v3/assessment_routes.py
This now starts the assessments correctly, although we still need to adjust pull_revision and push_results in the aqua-assessments repo so they run correctly.
> Fix assessment runner model

- .github/workflows/main.yml
- .github/workflows/pr.yml
- Makefile
- app.py
- test/conftest.py
- test/test_assessment_routes/test_assessment_routes.py
- test/test_bible_routes/test_revision_routes.py
- test/test_bible_routes/test_verse_routes.py
- test/test_security_routes/test_admin_routes.py
fix test to run during ci and a couple bugs
> fix test to run during ci

- bible_routes/v3/revision_routes.py
- bible_routes/v3/version_routes.py
- models.py
- review_routes/v3/results_routes.py
- test/conftest.py
- test/test_bible_routes/test_revision_routes.py
- test/test_bible_routes/test_version_routes.py
- test/test_security_routes/test_admin_routes.py
- test/test_security_routes/test_auth_routes.py
delemete for revisions and versions to update the deletme fields in the database instead of actually deleting the fields, the get methods updated to check for the delete flag
also linting
> update delete me workflow

- assessment_routes/v3/assessment_routes.py
- models.py
- review_routes/v3/results_routes.py
This fixes some issues with aggregation in the results routes. Also allows us to submit assessments via the new Modal _aws runner app.
> Aws new backend run assessments

- review_routes/v3/results_routes.py
I've added the /compareresults route, which seems to be working.
I also fixed the `aggregate="text"` query on the /results route, which had been grouped.
Removed the "include_text" option, because we don't use that, and it makes the SQL queries even more complex and slow. It's better to make a separate async API request to get the text.
> Add compare results route

- review_routes/v3/results_routes.py
Most of the changes here are just linting. The substantial changes are the lines towards the end.
> Fix result filtering by vref

- review_routes/v3/results_routes.py
This is a new route, allowing us to generate missing words data on the fly from the database, rather than hard-coding the comparisons into the results table.
> Add Missing Words route

- database/models.py
- review_routes/v3/results_routes.py
Add indexes on `alignment_top_source_scores` table. Remove print statements. Remove duplicate query initiation, which actually took a lot of time.
> Improve missing words

- bible_routes/v3/version_routes.py
- models.py
- notebooks/integration.ipynb
- test/conftest.py
- test/test_bible_routes/test_version_routes.py
PUT /version method modified, allowing to change any parameter besides the name, including the add to groups parameters, which will add a version to other group as long as you belong to that group, and you are the owner of the version
> Generic putversions/aqua201

- models.py
> owner_id nullable in version_out

- bible_loading.py
- bible_routes/v3/revision_routes.py
- notebooks/integration.ipynb
- test/test_assessment_routes/test_assessment_routes.py
- test/test_bible_routes/test_revision_routes.py
Test Performance added.
Temporary file deleted.
Batch processing on text_loading.
> Post revision performance/aqua215

- database/models.py
- security_routes/admin_routes.py
- security_routes/auth_routes.py
- test/conftest.py
- Token Route Modified
- Linting on database/models.py
- is_reference modified on conftest
> token route modified

- assessment_routes/v3/assessment_routes.py
- models.py
- review_routes/v3/results_routes.py
- test/test_assessment_routes/test_assessment_routes.py
- Missing words removed logic
- Testing assessments using missing words replaced by word-alignment
> Missing words removed

- assessment_routes/v3/assessment_routes.py
- models.py
- review_routes/v3/results_routes.py
- test/test_assessment_routes/test_assessment_routes.py
> Revert "Missing words removed"

- .github/workflows/dev.yml
- Makefile
- assessment_routes/v3/assessment_routes.py
- models.py
- notebooks/integration.ipynb
- review_routes/v3/results_routes.py
- test/test_assessment_routes/test_assessment_routes.py
> new github workflow and makefile

- app_test.py
- modal_test.sh
- models.py
- test/test_security_routes/test_admin_routes.py
Removing all code referring to dummy types
> Replace dummy types/aqua237

- docker-compose.yml
- security_routes/utilities.py
- We had the key hardcoded, changed to env variable
> key changed

- .gitignore
- assessment_routes/v3/assessment_routes.py
- database/models.py
- models.py
Ngrams are a new kind of assessment.
Each ngram has the ngram text and an ngram length (of the ngram text). See NgramsTable
An ngram can appear in multiple verses. See NgramsVrefTable
Not quite sure what "relationships" they need to the other tables, if any...
> Ngrams Table Schema

- Makefile
- notebooks/assessmentes_fromneon.ipynb
- notebooks/data_migration_fromneon.ipynb
- test/conftest.py
- test/test_security_routes/test_utilities.py
Testing for utils function, async testing, implementation of using async db
> Utils test

- assessment_routes/v3/assessment_routes.py
- notebooks/integration.ipynb
add notebook integration, add modal env in env
> add notebook integration, add modal env in env

- review_routes/v3/results_routes.py
Fixed an issue where get_text_proportions was averaging scores across all assessments.
> Fix text proportions bug

- review_routes/v3/results_routes.py
Part 2 - passing all my of linting tests locally now. Ran more manual testing as well.
> Fix TP linting

- models.py
- review_routes/v3/results_routes.py
- review_routes/v3/search_routes.py
- test/review_routes/test_results_routes.py
- test/review_routes/test_search_routes.py
This is a database query route I need for the AQuA agents assessment. Currently I'm querying the database directly, but here's an API route instead, which is a safer way to do it.
> New routes for aqua agent
